hotosm/raw-data-api

- docs/GETTING_STARTED_WITH_DOCKER.md
This PR will close [issue 5](https://github.com/hotosm/export-tool-api/issues/5)
The docker documentation is greatly written. I followed the instruction and updated it a bit. Following it, I was able to spin up the containers, authenticate, export data without any hassle. Great job @kshitijrajsharma !
> Updated docker documentation

- API/auth/__init__.py
- API/auth/routers.py
- requirements.txt
implemented authorization using osm-login-python
> Authorization using Osm-Login-Python

- .github/workflows/Unit-Test.yml
- Now unit test will build from loading intiial pbf osm file to extracting data out of it , which is enabled by new ```run.py``` on loading side ! No longer need to use sample sql file and also it will showcase how we can do it from top to bottom
> Unit test build end to end 

- .github/workflows/publish_mkdocs.yml
- README.md
- docs/mkdocs.yml
- docs/src/index.md
This PR gives credit to all developers envolved/ engaged on the project on documentation
> Credit to All developers contributed to project

- .gitignore
- infra/main.tf
- infra/provider.tf
- infra/variables.tf
- Add all raw-data backend and database components
- Add .gitignore to exclude terraform state files and lock files
TODO:
- Add more addresses to the VPC and add additional subnetworks for private and public traffic.
- Add firewall rules to restrict access to DB and the VM
> [WIP] Initial Infrastructure code

- API/raw_data.py
- backend/raw_backend
- src/query_builder/builder.py
- src/validation/models.py
- Quick PR to support request coming from turkey earthquake , To filterout damaged building with specific conditions only which requires support for AND Clause and OR clause for the same request !
> Support for and Clause on POST Snapshot 

- backend/field_update
- backend/raw.lua
- backend/raw_with_ref.lua
- Used centroid of the feature for the intersection for ways_poly
> Enhance Query to do Field update 

- .github/workflows/Unit-Test.yml
- .github/workflows/black-for-PR.yml
- .github/workflows/black-formatter.yml
- .github/workflows/build.yml
- .github/workflows/code-check.yml
> Bug Fix for Workflow Run

- infra/docs/testing.md
- infra/production/tests/compliance/cloudfront.feature
- infra/production/tests/compliance/s3.feature
- infra/staging/tests/compliance/cloudfront.feature
- infra/staging/tests/compliance/s3.feature
Add terraform-compliance BDD test feature files and initial documentation.
> Add BDD test components for compliance tests

- infra/staging/main.tf
- Add a locals for mandatory and resource-specific tags and add them to all resources that will take it.
> Add tags to all resources that will take them

- infra/production/main.tf
- Add resource tags for all production resources that will take them
> Add resource tags to all accepting resources

- infra/production/main.tf
- Key Vault was inaccessible by Terraform cloud because public network access was cut-off. Reverted that mistake. Also added a warning message right above the line explicitly stating public access is required for managing resource through Terraform
> Make Key Vault accessible to public networks again

- src/query_builder/builder.py
- src/validation/models.py
- tests/test_API.py
- Resolve #110
- Supports extraction of features as centroid with centroid parameter set to true on api request body
> Feature Support Centroid 

- infra/production/main.tf
Manually deleted the original disk by mistake. Fixing this but with a smaller disk.
> Fix secondary volume size

- infra/production/main.tf
- infra/production/variables.tf
> Increase backend VM capacity

- backend/raw_backend
- backend/replication
- infra/systemd/raw-data-backend.service
- infra/systemd/raw-data-backend.timer
- Skips raw update , Partial version on PR #112
> Timer Service for backend and Skip update 

- backend/Readme.md
- backend/raw_backend
- backend/replication
- Adds support for custom geojson filter on replciation so that raw data api can be up and running for custom area 
TODO : 
Parallel Country Update 
TEST : 
Example for pokhara 
```
python raw_backend --insert --replication --boundary pokhara.geojson
```
> Feature Custom Filter Geojson for Replication

- docs/src/installation/configurations.md
- src/query_builder/builder.py
- Fixes bug on selection of shapefile exports , Updates typo on readme
> HOTFIX: Bug fix on Readme and selection

- API/api_worker.py
- src/validation/models.py
Added recurring export feature on s3 upload , it will give option to user that download link will always be constant and updated when done frequently
> Feature : Recurring exports

- config.txt.sample
- docs/src/installation/configurations.md
- src/config.py
- Add better config defaults in config.py
- Remove some uncertainties from configuration documentation
- Make configuration sample file more complete
> Add better configuration defaults

- backend/field_update
- backend/replication
- backend/sql/post_indexes.sql
- backend/sql/pre_indexes.sql
- src/query_builder/builder.py
This PR updates the backend field update so that if feature is outside the loaded country it will have 0 field
> Hotfix : Update Country as 0 if not intersected 

- API/raw_data.py
- README.md
Introduces queue name defined from API itself
Name is following , They can be used directly in order to launch workers respectively 
- recurring_queue 
- raw_default
> Feature : Queue Name

- backend/field_update
- backend/replication
- src/query_builder/builder.py
- tests/test_API.py
- Fixes CI build due to column name
> Fix : CI Build

- API/api_worker.py
- API/tasks.py
- Dockerfile
- backend/sql/update_countries.sql
- src/app.py
- Adds tippecanoe docker support
> Feature : Tippecanoe Docker Support

- API/api_worker.py
- API/tasks.py
- Fixes the bug of HDX folder structure from API , now follows , s3/HDX/ISO_3/export_name
- Fixes the bug of task started status , now it is enabled by default
> Bug Fix : HDX Folder Structure on S3

- API/api_worker.py
- Adds Metadata of exports in .zip using Readme.txt , Example below : 
```
Exported Timestamp (UTC+0000): 2023-11-21 08:28:27
Exported through raw-data-api (https://github.com/hotosm/raw-data-api) using OpenStreetMap data.
Learn more about OpenStreetMap and its data usage policy : https://www.openstreetmap.org/about
```
> Dump export metadata to .zip file 

- API/auth/__init__.py
- API/auth/routers.py
- src/app.py
- Fixes leaked db connection issue on auth , which was causing cursor closed issue and also memory issue in the database , it closes the connection after transaction is performed
> Bug - Fix : Fixes Leaked Connection 

- API/api_worker.py
- API/raw_data.py
- src/validation/models.py
-  Does not require permission for bind_zip false if it is within 200 sqkm
> Enhance Bind Zip and updated Permission

- API/api_worker.py
- README.md
- requirements.txt
- Adds support for sozip while compression
> Feature : Sozip 
